
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false

    - name: Install and Build
      run: |
        yarn --frozen-lockfile
        yarn build  
    
    - name: Move and make
      run: |
        mv favicon.ico .vitepress/dist/
        cd .vitepress/dist/
        touch .nojekyll
        echo 'tolive.toyou.xyz' > CNAME

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .vitepress/dist/